name: update_table
on:
  push:
    branches:
      - 'main'
#  schedule:
#    # 毎週木曜午前10時に更新
#    - cron: '0 1 * * 4'

env:
  GOOGLE_SHEET_KEY: ${{secrets.GOOGLE_SHEET_KEY}}

jobs:
  # データの取得
  fetch_table:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install gspread
          pip install dotenv
          
      - name: Run script
        run: |
          mkdir ./dist
          cp -f ./public/index.html ./dist/index.html
          python ./src/main.py

      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
